Script started on 2017年03月14日 (週二) 22時10分35秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/0314 $[00m whoami;pwd
pd2vm
/home/pd2vm/0314
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/0314 $[00m git config -l
user.email=hspss90272@gmail.com
user.name=yeadra
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/0314 $[00m git clone htt[s:\\[K[K[K[K[Kps/[K://githubc[K/co[K[K[K.com/yeadra/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Compressing objects:  50% (1/2)   [Kremote: Compressing objects: 100% (2/2)   [Kremote: Compressing objects: 100% (2/2), done.[K
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/0314 $[00m exit

Script done on 2017年03月14日 (週二) 22時11分26秒
